mysql:
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  database: ${MYSQL_DATABASE:games}

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
#    show-sql=true

freenba:
  api:
    host: free-nba.p.rapidapi.com
    base-url: https://${freenba.api.host}
    key: ${NBA_API_KEY}
    headers:
      x-rapidapi-host: ${freenba.api.host}
      x-rapidapi-key: ${NBA_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true